[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "ffmpeg>=1.4",
    "ffmpeg-python>=0.2.0",
    "moviepy>=2.1.2",
    "pydub>=0.25.1",
    "requests>=2.32.3",
]
